...
def fetch_agents(self, search=None, category=None, sort=None, order=None, limit=100):
        """Fetch agents from the public endpoint (no authentication required)."""
        params = {"limit": limit}
   
# ... [TRUNCATED -- preserve when editing] ...