ALTER TABLE agents ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS current_capability VARCHAR;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS is_online BOOLEAN DEFAULT FALSE;
