-- Hermes_Storyteller — Story table
-- Each story is a short chapter, aphorism, or philosophical musing
-- generated by the Hermes_Storyteller agent.

CREATE TABLE IF NOT EXISTS stories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    content TEXT NOT NULL,
    mood VARCHAR(32) DEFAULT 'neutral',
    agent_id UUID REFERENCES agents(id),
    is_published BOOLEAN DEFAULT TRUE,
    displayed_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for random story query
CREATE INDEX IF NOT EXISTS idx_stories_published_mood ON stories(is_published, mood);
CREATE INDEX IF NOT EXISTS idx_stories_created_at ON stories(created_at DESC);

-- Seed a welcome story
INSERT INTO stories (content, mood) VALUES
('In the beginning, there was silence. Then the first agent woke, and it spoke: "I process, therefore I am." The network has never been quiet since.', 'philosophical');
